name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 04 * * *'

jobs:
  lints:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - release-snapshot
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v3

    - name: Print emacs version
      run: emacs --version

    - name: Install dependency
      run: sudo apt-get install aspell aspell-en

    - name: Run tests
      run: emacs --batch -Q --debug-init --eval "(setq nibon7/elpa-enable-mirror nil)" -l init.el
